test:
  _target_: src.datasets.CustomDirAudioDataset
  audio_dir: ${custom_audio_dir}
  transcription_dir: ${custom_transcription_dir,null}
  instance_transforms: ${transforms.instance_transforms.inference}
